### ISSUE TITLE
Extraction list validation

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#11]
Multiple users of poseidon2 reported issues with the filter file for the `extract` command. For effective extraction the user has to prepare a perfect (no spelling mistakes, no trailing tabs) list of individual and and group IDs. This is sometimes difficult to achieve. 

poseidon2 has no mechanism to check for wrong input - it just silently ignores wrong entries. We should come up with some better feedback in trident.

**Comment by scarlhoff** [comment]
Hi! To avoid mistakes when creating the filter list, I wrote a short bash script utilising the .fam file. You put in all entities you want to extract and it creates a file with group and individual IDs. Idk if it's useful but it exists :D

**Comment by nevrome** [comment]
Excellent! I closed this issue, because trident now checks for and reports entities (packages, groups, individuals) that do not exist in the repository (`-d`).

Where exactly does your script fit into the pipeline? I'm just curious if there is something we can do to make data extraction with `forge` more smooth.

**Comment by scarlhoff** [comment]
Well it's just very short and simple. You just put in all entities you want to extract (Pop), the path to the fam_file and an output_name. Upon execution the script then prints column 1 and 2 of the fam_file, greps all $POP and saves them in output_name.txt
Then you just use `poseidon2 extract output_name.txt <input_package> <output_directory>`
I can send it to you if you want

**Comment by nevrome** [comment]
Ah! I see. That is indeed useful for `poseidon2 extract` and `plink extract`! 

But I think for `trident forge` it is not necessary, because trident allows to directly list individuals, ja?

**Comment by scarlhoff** [comment]
Should be. I wrote it before `forge` was opened for testing, so ;D
