### ISSUE TITLE
forgeString should have an negation option to exclude entities

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#115]
We already discussed this many moons ago and Margherita had a usecase today where this concept would have been useful. I imagine an interface like this:

`-f "*my_package1*,*my_package2*,!<that_one_individual_I_don't_want>,!that_group_I_don't_want"`

**Comment by stschiff** [comment]
Yes, I think that would be very useful indeed! I was thinking about a similar option for `fstats` (although that functionality is anyway currently under question whether we want to keep it in trident).

So yes, I'm supportive of that (ignoring my bizarre Todo-list right now).

**Comment by stschiff** [comment]
So this would be a feature for both `fetch` and `forge`, right?

**Comment by nevrome** [comment]
Right - we could use the same parser for both. Although with `fetch` operating on a package level I don't see how the feature would be used there :thinking:

**Comment by nevrome** [comment]
Implemented in v.0.24.0
