### ISSUE TITLE
GoldenTests in Poseidon should use standalone test server

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#125]
We currently rely on the remote server for our Golden Tests (`fetch`, notably, `list --remote` isn't tested at all currently). This isn't optimal. It would be better to be able to have the tests to be fully self-contained, and also work without internet access. One solution would be to spin of a minimal http server on `localhost` and to access that during the tests.

**Comment by nevrome** [comment]
This will finally be solved with #234.

**Comment by stschiff** [comment]
Oh yes, and I will try to actually get #234 in ASAP.

**Comment by nevrome** [comment]
This is solved :+1:
