### ISSUE TITLE
Switch to Haskell PVP from SemVer

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#129]
Haskell software is supposed to follow the [Haskell Package Versioning Policy](https://pvp.haskell.org/) which unfortunately [differs](https://pvp.haskell.org/faq/) from Semantic Versioning. We should switch to allow for a submission to hackage one day.

**Comment by stschiff** [comment]
Uff... OK, I've submitted multiple packages to hackage and never even looked at these specs... I skimmed through those quickly and couldn't really find a compelling difference, other than they don't really seem to attach much semantic meaning to the major version number... I think we're fine...

**Comment by nevrome** [comment]
Hm. I don't want to ignore an established standard. People should be able to rely on version numbers. Maybe we solve it as this random dude suggests: https://taylor.fausak.me/2016/12/28/problematic-versioning-policy/

> Update 2020-05-08: Since writing this, I have softened my position. I no longer think Haskell packages should use SemVer since the switching cost would be so much higher than any marginal gains from a better versioning scheme. Instead I suggest that packages use versions like 1.major.minor.patch, which is broadly compatible with both SemVer and the PVP. 

That boils down to jumping to `1.1.0.0` and then following semantic versioning with the last three numbers. Let's keep this in mind for when we leave the beta state.

**Comment by stschiff** [comment]
Hmm... but switching to a four-letter version code is also confusing. I'm not sure I get this fully. So with a version A.B.C, for breaking changes, PVP would like to increment the A.B, which I think agrees with SemVer, right? Then, for non-breaking changes, they ask that A.B **may** be incremented, while C **must** be incremented. But I don't get it. In SemVer, a new and non-breaking API addition should increase B, so that seems compatible then... I'm confused by the fact that PVP needs C to be higher, even if A.B have been increased?

So I see really only superficial differences... or perhaps I don't get it.

Can you point out a recent Semver-increase in poseidon-hs which would be truly incompatible with PVP?

**Comment by nevrome** [comment]
OK - so to my understanding PVP can be described as SemVer with an additional number prepended: https://pvp.haskell.org/faq/#how-does-the-pvp-relate-to-semantic-versioning-semver. We're still fully compatible with PVP, because we haven't put out `1.0.0` yet.

SemVer boils down to A.B.C with A for breaking changes, B for additional features and C for patches/fixes. As we haven't incremented A yet, we use B for breaking changes AND additional features. Afaik that's not unusual for beta software.

PVP is also A.B.C, but B is for breaking changes, C is for additional features and patches/fixes CAN but don't have to go into a D. D can be omitted. What's the purpose of A then? Well...:

> One popular way is to use the first component of the major version to denote “epochs” of APIs (c.f. Edward Kmett’s packages) and allowing development (with major version increments) to continue independently in different epochs. This allows to avoid suffixing packages names with numbers to denote different epochs (e.g. base2-1.0, base3-1.0, base4-1.0).
>
> A different way to see the 2-part major version component is to allow for nuanced signaling of large vs. not-so-large backward incompatible changes.
>
> Yet another way is to use the first component for marketing purposes, e.g. to increment to “1.0” when a package is considered mature.

So: As soon as we go to `1.0.0` and stick to SemVer we won't be compliant any more. That's why I suggest to go to 1.1.0.0 and then ignore A.

**Comment by nevrome** [comment]
We have now switched to PVP, starting with v1.0.0.0
