### ISSUE TITLE
Better handling of incompatible SNPs during forge

### ISSUE THREAD

**Issue by bvernot** [poseidon-framework/poseidon-hs#130]
Currently, if there are incompatible snps (i.e. A,T in one dataset and A,G in another), an error is thrown when the first snp is detected. This makes it a little challenging to debug/fix, because you don't know how many incompatible snps there are / where they are. It would be great if there were a simple report given about all incompatible snps.

Similarly, you could imagine a flag to remove these incompatible snps.

**Comment by stschiff** [comment]
I see. Yes, I've built it quite brittle on purpose, as I'm anxious users might get ill-formed data. But indeed, one could change this to a warning and simply say that the SNP is skipped. I already do that with other types of inconsistencies (like inconsistent SNP names and such)
