### ISSUE TITLE
define snp set with bed file during forge

### ISSUE THREAD

**Issue by bvernot** [poseidon-framework/poseidon-hs#131]
It would be great to allow the user to define a set of sites to keep when forging, that is neither the intersection or the union of the sites in a set of packages.

**Comment by stschiff** [comment]
Yes, that would be no problem at all to implement... one would have to decide what to do in case there are sites requested that simply aren't in the dataset... mark them missing or simply skip, I guess those are the two options.

**Comment by bvernot** [comment]
Hm yes, I'm not sure what would be best. If you mark them missing in the
whole dataset (and I suppose to set N N as the two alleles), then the
output would always be consistent and predictable. But maybe completely
missing sites would cause issues with some software?

**Comment by nevrome** [comment]
Implemented in v0.23.0
