### ISSUE TITLE
trident summarize fails

### ISSUE THREAD

**Issue by bvernot** [poseidon-framework/poseidon-hs#138]
It seems that `trident summarize` fails - the British spelling "summarise" is required.

This is anti-American bias! :)

![hulk-hogan-guitar](https://user-images.githubusercontent.com/9371506/138460232-09fb1ac9-595b-448f-86d9-b9d19b756270.gif)

**Comment by nevrome** [comment]
I was curious if there is an easy and elegant way to implement this. Turns out: [apparently not](https://stackoverflow.com/questions/70057060/subcommand-synonyms-for-optparse-applicative). We would probably have to go for a hacky solution. That's a pity.

**Comment by stschiff** [comment]
Hmm. OK. I didn't have my hopes up for that anyway. My humble plan would have been to just define `summarize` as separate command and use "Synonym for summarise" as the help text for that command. I think it's neither hacky nor unclear.

**Comment by bvernot** [comment]
To me Stephan's plan would be clear.

**Comment by nevrome** [comment]
I was overthinking this. Implemented in literally 2 minutes in v0.24.1
