### ISSUE TITLE
Trident forge stops working due to additional space in forge_file

### ISSUE THREAD

**Issue by neija2611** [poseidon-framework/poseidon-hs#139]
The Trident forge run stopped without giving an error message at an additional space in my forge_file. No data from that point was further processed. I ended up with a package containing all expected information (.bib, .geno, .ind, .janno, .snp, .yml -files) but just for the populations included in my forge_file listed before the additional space.

**Comment by stschiff** [comment]
Thanks for reporting. Will look into it

**Comment by nevrome** [comment]
This throws a proper error now in v.0.24.0.
