### ISSUE TITLE
Reorder all relevant data types/instances/lists according to the new .janno column order

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#156]
See the discussion in #152. The PR was lazy in that regard, which might cause maintenance issues eventually.

**Comment by robopsychologist** [comment]
Hey @nevrome! Its Eddy - we emailed and you mentioned there were some Poseidon issues that were open! If you want I can take a quick look at this one and submit a PR? Lets me get aquatinted with the code base a little bit :)

**Comment by nevrome** [comment]
Hey Eddy - sounds good to me! The change to Poseidon v2.5.0 was pretty massive and we left this tedious reordering task open. A PR to fix that would be very welcome.

The now correct order is defined [here](https://github.com/poseidon-framework/poseidon2-schema/blob/master/janno_columns.tsv). In the code only the `jannoHeader` in Janno.hs features the correct order already. But there are numerous other contexts where this order is not established yet. Mostly in Janno.hs, but also once in CLI/List.hs.

We currently have #163 open, which also introduces some significant changes, but in an entirely different domain of the code. So I don't see a big danger for merge conflicts. Maybe it would nevertheless make sense to fork from there, because it is imho ready for merging :thinking:

**Comment by nevrome** [comment]
I think this is resolved now.
