### ISSUE TITLE
EntitiesList semantics

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#161]
We currently have the option to specify entity lists by including and excluding entities. This is currently used in `forge` and `fetch`, and it is also used outside, in `xerxes`. 

The current semantics (not part of the data types, but of the `forge` and `fetch` implementations) are, that all includes are executed, before any excludes. An alternative would be to execute includes and excludes in order. This has two advantages in my view:

1) Less obfuscated:
Currently, if the user species `a,-<b>,c,-<d>`, she needs to reorder these in her head to predict the result.

2) More power:
There is actually a good reason for executing these operations in order. For example:
`*PackageA*,-GroupB,<IndidivualC>` could be useful if `<IndividualC>` would be part of `GroupB`. In that case, I would want to exclude all individuals _but_ `<IndividualC>`. I'd argue this to be a common use case, and this would not be possible in the current semantics. Currently, you would first include `<IndividualC>` and then exclude it again by excluding entire `GroupB`, to which `<IndividualC>` belongs.

I think this would be a relatively small change, and I'm happy to take a stab. It can easily be implemented using recursion.

**Comment by nevrome** [comment]
Argument 2 is a pretty strong one! So I guess we should indeed change this. Happy to be involved.

**Comment by stschiff** [comment]
Good. I've already switched to `EntitiesList` in `xerxes` with the ordered semantics and happy to make this change for `fetch` and `forge`. Will submit a PR

**Comment by nevrome** [comment]
To my understanding this is fully solved by #163. I close the issue.
