### ISSUE TITLE
Rename the update subcommand

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#164]
The update subcommand was designed to support the work with the public repo. Its purpose is to rectify some technical aspects of poseidon packages after manually (!) updating them. It does not adjust the structure of packages from old to new versions of the Poseidon schema.

As predicted by you, @stschiff, this is not what users expect. @arthurKocher contacted me exactly about this confusion. Maybe we should discuss two options:

- Should we rename `update` to reduce this confusion? What would be a clear yet concise verb to describe what `update` currently does?
- Should we think about implementing a "real" `update` command, that takes packages in old schema versions and automatically brings them to the latest (or even any newer/other) version? It would be some work, yet by no means impossible. But is this a good investment of our time?

**Comment by nevrome** [comment]
Some ideas for the renaming of `trident update` after discussing this with Arthur:
- `trident rebuild`
- `trident rectify`
- `trident harmonise` (and `harmonize`)

**Comment by stschiff** [comment]
Is there not any way we can simply beef up `update`? It's deeply unsatisfying to have another command which is called something more obscure, but in fact it performs a kind of update, all the while having an actual `update` command which doesn't really update. I think I would currently lean against bringing in an additional sub-command and would rather create some kind of option that automatically performs (simple) version upgrades. 

A more intelligent version of `update`, if you will... which
1) Checks for outdated checksums
2) Checks for the format of the Janno-file and suggests or performs changes that make it version-conformant
3) updates the Version and the changelog etc.

It seems this is - at least conceptually - possible without introducing a new command. What do you think?

**Comment by nevrome** [comment]
Would be great, but I see some technical difficulties. Reading and validating of packages and .janno files is a pretty heavy, complex and static (!) machinery. How can we avoid code duplication when we have to read different Poseidon versions for a "real" `update`?

**Comment by stschiff** [comment]
Well, the "real" update function will be challenging, no question. My point was that I'd rather somehow integrate that feature feature into our existing `update` subcommand, perhaps using a special flag, than introduce a new subcommand. It's really just a point about the API, not about the internal implementation (which can be a completely different function or Haskell module).
