### ISSUE TITLE
Multiple input files for trident init?

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#174]
As `forge` is now capable of directly swallowing unpackaged genotype data, `init` became essentially a special case of `forge`. Both take input data and return a Poseidon package.

I still think we should keep `init` around, because it mirrors other cli tools (git, stack, etc.) ,because it is didactically valuable for people new to Poseidon and because it handles the **one-dataset case** much faster than forge (it only copies the data without streaming through it).

But maybe we could enhance `init` and allow it to take multiple genotype datasets as input. For this **multi-dataset case** it could internally fall back on the code in `forge`.

**Comment by nevrome** [comment]
Well - this post was initiated by a confused user, who asked me how to do a "forge-init", so how to create a new package from multiple sources. It's counter-intuitive that one has to use `forge` in this case, although the description of `init` aligns much better with what you want to do: Create a Poseidon package.

The more I think about it, the more I feel we could deprecate init and instead define init as a special case of forge. The name "forge" is already general enough, we would avoid this confusion and we would have to maintain one subcommand less.

**Comment by stschiff** [comment]
Ah OK... I see. Yes, perhaps we should do this... but does forge already have the same options as init, with respect to "minimal" packages, and providing bib-, janno-files and so on?

**Comment by nevrome** [comment]
Yes - this should be all there. Of course we would have to check carefully if this change would have any other unforeseen consequences.

There are also two strong arguments against it:
- We would certainly break many (automatic) Poseidon workflows if we remove `init`, because they all start with that right now.
- `init` shines in the **one-dataset case** mentioned above.

So: I'm undecided.

**Comment by stschiff** [comment]
I think the best solution is:
* Keep `init` around as a command, but indeed allow it to use multiple genotype sources
* Internally implement it using the Forge CLI function, to remove redundant code.

That way we will have win-win
* remove code redundancy, increase maintainability
* keep backwards-compatibility with existing work-flows using `init`
* be newbie-friendly by providing an `init`

**Comment by nevrome** [comment]
After rereading this discussion I agree now with your statement from May 19, 2022: Both `forge` and `init` have their purpose as they are. And this justifies their differences in implementation. Implementing `init` via `forge` would be pretty inefficient: `forge` loops through the genotype files, after all, which `init` does not need to do for the most common usecase.

I close this issue for now. Please feel free to reopen.
