### ISSUE TITLE
Duplicate individuals management 

### ISSUE THREAD

**Issue by ltcrod** [poseidon-framework/poseidon-hs#179]
While working with Trident to manage EIGENSTRAT packages, I found that having duplicate samples in two or more datasets really slows the workflow down: if I want to extract sample A that is present in both my packs X and Y, I have to first subset one of the two by removing all the individuals (or pops) that are in the other one, or rename them. 
This basically doubles the time required, and this happens pretty often when combining and subsetting many different published datasets and private ones at once. 

I guess a possible solution would be improving the trident forgeString synthax, so that one could hierarchically specify from which population/package trident should select a sample, or from which package a population should be taken.

**Comment by nevrome** [comment]
In today's poseidon meeting @stschiff proposed a pretty interesting idea how to handle duplicates in `forge`, which is a little simpler than my suggestion above. Simpler also means more robust, which compensates a slide lack in elegance. I think this is worth a try, although sometimes the implementation uncovers unforeseen issues.

Imagine a user Bob who has a package `X` with an individual `A` in group `P` and a package `Ỳ` with an individual `A` in group `P`. Bob wants to forge them with a forgeString `<A>`. Stephan's idea now entails, that `A` gets renamed internally to `X.P.A` and `Y.P.A`. This renders Bob's initial forgeString invalid. He gets an error message like this: `Error: <A> exists multiple times in this data selection: <X.P.A>, <Y.P.A>. Please specify!`. He could then edit his forge string to either `<X.P.A>`,  `<Y.P.A>` or `<X.P.A>,<Y.P.A>`, to include one or both of the iterations of `A`. In the output the individual will not be called `A` any more, but `X.P.A` or `Y.P.A`. This is slightly verbose, but Bob can rename that later if he so pleases.

**Comment by stschiff** [comment]
Yes, that summarises what I meant. 

But on a much more radical note: Why not simply allow duplicate names, and then `<A>` would simply catch all individuals named `<A>`? Going back to what I said back in June: What's the harm in fully allowing duplicates in trident? 

As a first step, we could simply output warnings in `readPoseidonPackage`, and nowhere else... I think there is no problem in any downstream step. Forge will simply go through, by selecting all individuals with that name and causing duplicate names in the forged output. When then someone reads the forged package again with some `trident` function, there will be a warning about duplicate individuals. The same happens in `Xerxes`, since it calls `readPoseidonPackage`... all analyses (FStats and so on) will go through as is, simply by taking in both samples if they are not renamed.

I think I'm voting for the simplest here... :-)

**Comment by nevrome** [comment]
I do not think that it is a good idea to ignore duplicates. Allowing them causes all sorts of confusion and makes it extremely easy to arrive at wrong results. I remember multiple instances where I had forgotten a derived, forged repo below my respective `-d`, when compiling a new forge operation. I am now absolutely convinced that a hard rule of no duplicate PoseidonIDs in a given dataset will prevent many wrong results in the future.

I suggest the following solution:
1. `readPoseidonPackageCollection` and `readPoseidonPackage` fail hard by default, if any duplicates are detected
2. An additional command line option `--allowDuplicates` allows to proceed anyway
3. `forge`, `fstats`, and any other command where it matters will require specification with `Package.Group.Individual` as suggested above

This is exactly the opposite of your suggestion, but I think it is in the user's interest to not have duplicates in their dataset.

**Comment by stschiff** [comment]
OK, I did not think of the annoying problem of having forgotten packages under `-d`, which has happened to me too. OK, I think you're right.

I think for the specification language thing, we need to be careful how to implement this, though. What I proposed, and what you summarised above is that duplicate individual names get renamed... but when? The naive solution would be to rename right when duplicates are observed... but then, if the user as given `<A>`, you wouldn't arrive at "Duplicates found ... please specify!". Rather you would get `<A>` not found... so implementation will need to be a bit careful in the logic and the order of checks and renamings.

Perhaps the easiest is to do the rename right within `readPoseidonPackage` and `readPoseidonPackageCollection`, but give a warning when it happens, like "found duplicate individual name 'A', renaming to 'X.P.A' and 'Y.P.A'" before giving the expected error output "Entity <A> not found."

**Comment by nevrome** [comment]
Right - the implementation is not trivial. The details usually emerge when you start to change the code. This is on my list for a long time, but I don't mind if you want to tackle it. We just have to communicate it here, when one of us starts to work on it, to prevent duplication of effort.

**Comment by nevrome** [comment]
This should finally be solved in v1.1.7.0: https://github.com/poseidon-framework/poseidon-hs/releases/tag/v1.1.7.0

I close this issue now. Please let me know if it does not enable the desired usecase, @ltcrod :+1:
