### ISSUE TITLE
Genotype conversion memory footprint. Covert to stream conversion? 

### ISSUE THREAD

**Issue by TCLamnidis** [poseidon-framework/poseidon-hs#181]
Admittedly, my use case here is unusual, so this issue is unlikely to affect more users, but:
I have a very large dataset that I am trying to convert from EIG to PLINK using `trident genoconvert`. Submitting the job to a scheduler revealed that the job fails because it runs out of memory after processing part of the dataset. 

My dataset is 154,353,735 SNPs long and 4GB of memory will only run through ~9M of these SNPs. Providing ~ 68GB of memory will probably get things working, but it seems a very hefty amount of memory to require for such a conversion. Is there a reason genotype conversion is done in memory instead of as a stream that writes the new genotype format as it works its way through the input without overloading the memory?

I can see that creating a potentially truncated output file is not a good idea, but what about streaming to a temporary file that then gets renamed?

**Comment by nevrome** [comment]
I can confirm @TCLamnidis' observation: There is a space leak in `genoconvert`. It already consumes about 300Mb for a 1240K dataset. Either we missed that in the past, or we introduced this issue recently. `forge` does not leak.

**Comment by stschiff** [comment]
This has been fixed through #188. It's now in master and will end up in the next release.
