### ISSUE TITLE
From `v0.27`, `--forgeFile` and `--forgeString` can't be appeared together. Can still do it in `v0.26` .

### ISSUE THREAD

**Issue by huanglei-artificium** [poseidon-framework/poseidon-hs#183]
I would like to merge samples from different packages. For some packages, I want to select tens of individuals, so I use a file; while for others, I only need to select a few of them, and I can use string. I prefer to create a different file/string for different packages.
![image](https://user-images.githubusercontent.com/56875428/174978826-73dbd3fc-0646-48ac-a141-5b25a3b999ef.png)

**Comment by nevrome** [comment]
Solved in #192. Will be part of the next release.
