### ISSUE TITLE
genoconvert should create necessary output directory 

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#184]
Using `genoconvert` with `-o` can result in an error "openFile: does not exist (No such file or directory)".

I think we should try to create the output directory if it's given. (I can do that, just a reminder)

**Comment by nevrome** [comment]
Same for `fetch`

**Comment by stschiff** [comment]
I don't think so. Fetch has a call to `createDirectoryIfMissing` already.

**Comment by stschiff** [comment]
No. I stand corrected. That's only for the tempDir. I'm fixing that too.
