### ISSUE TITLE
Github actions workflow optimization

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#19]
It should be possible to further reduce the runtime.

**Comment by nevrome** [comment]
Here is a workflow that seems to be more thought through: https://medium.com/@_KtorZ_/continuous-integration-in-haskell-9ad2a73e8e46

**Comment by stschiff** [comment]
Looks very good to me, what's proposed in that medium article!

**Comment by nevrome** [comment]
The release action does not seem to cache correctly.

**Comment by nevrome** [comment]
Removed caching from the release action in 1527aedfde5dbbd173029238e1645a4578addf9f - does not make much sense. 

I'm happy with the github actions like this and will close this issue for now.
