### ISSUE TITLE
bib-file consistency check in validate is leaky

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#199]
I'm looking at [the code lines](https://github.com/poseidon-framework/poseidon-hs/blob/d9249712aa4ef2332928c2eb7cda6ebb864f1e4d/src/Poseidon/Package.hs#L338) which call `checkJannoBibConsistency`, and I think it's a problem that they are only called when a bib-file is present. I think there are cases where - for example - there are bib-keys in the Janno file, but no bibtex-file present, which should obviously be flagged.

**Comment by nevrome** [comment]
Ja - that sounds like a good idea. Should be a warning.
