### ISSUE TITLE
Use Janno-files in List Command?

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#2]
Now that we have a Janno-Parser, should we somehow make use of it in the `list` subcommand?

Right now we have `packages`, `groups` and `individuals`. Perhaps one could use information from the Janno file in these summaries.

**Comment by stschiff** [comment]
This has become partly obsolete with the nice `summarise` command, but still worth considering to put some of the janno-information in the list outputs.

**Comment by nevrome** [comment]
Implemented in #66
