### ISSUE TITLE
The old python code should go to another repository

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#20]
For the sake of a tidy repository.

**Comment by stschiff** [comment]
Ah you found it, didn't you? :-) OK, I agree.

**Comment by nevrome** [comment]
Well... :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/10789038/101295659-389eb980-381f-11eb-8ac0-12a935827059.png)

**Comment by stschiff** [comment]
Yes, let's remove it. I can put a PR as soon as I've finished the current bugfix

**Comment by nevrome** [comment]
Removed in #29.
