### ISSUE TITLE
Improve client-server interaction and manage old repo versions

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#203]
With the upcoming schema update, we need to deal with this in trident. Here are some thoughts, combined with the ones from you, @nevrome, on Slack:

- [ ] `fetch`: New versions of packages should only be considered for download if their Poseidon version can be parsed by the trident version that is being used. We want to avoid that someone overrides a package that they can't read anymore.
- [x] The upcoming version 2.6.0 should be fully backwards compatible with 2.5.0 as far as I can see, so we can make use of the version checks using a range from 2.5.0 to 2.6.0. At least an updated version of trident can then read old 2.5.0 packages
- [ ] Snapshot of old-versioned Poseidon packages -> This was a proposal by you, @nevrome, which is interesting, but I don't really know how that would work. Would we simply ask people to use a different remote URL and run a separate server? That would be possible and doable easily, but it might become complicated to maintain a stack of server instances for differently versioned packages in the future... Also, with the current version of trident, there would be no way that the server can relay a message to the client (such communication exists as a stub on the server side as `/compatibility` API, but is not implemented on the client side currently), see next point:
- [ ] I think we should change the client-server communication further, and for example have the client submit its own version for every request. So then every time the client makes a request to the server, we should implement the possibility for a polite decline with an error message that the client can report to the user. I will look into this.

**Comment by nevrome** [comment]
Sounds good and doable to me.

Regarding the server versioning: It's certainly necessary to report (package) version incompatibilities on the client side. But I don't think we should enable `fetch` to access old package versions. In my opinion it's enough to have one server with exactly one set of packages (the latest). If somebody runs an incompatible, outdated version of trident, then they should get a message that reports the issue and the relevant options:

1. "Download and install a new version of trident and update your workflow to the new schema version. Here is the schema changelog and the published data changelog."
2. "Continue working with an old stack. The old data is available **here**."

And **here** could be a download page with a number of snapshots of the repository in .tar.gz archives. Either for everything or for individual packages. This is not fancy, but perfectly reasonable. We should introduce versioned states of the published data repo for that. And a general, high level changelog.

Can you come up with a user story where this solution is not sufficient? The alternative, over the top solution would be do store the entire history of the repo on the server and allow downloading arbitrary package versions (e.g. "Give me version foo of package bar" or "Give me the latest version of package bar for poseidon schema version foo"). This would be super cool, but difficult to implement with questionable payoff. I think I would vote for the simple solution.

**Comment by stschiff** [comment]
Yes OK. I like all this. So then we need an overall versioning of the public repo. I will make an issue. I think transitioning to Poseidon Schema 2.6.0 could be the first instance where we simply offer the state of the repo now as the first packaged legacy repo.

**Comment by nevrome** [comment]
I think this issue is fully superseded by now.
