### ISSUE TITLE
Outsource analysis modules

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#22]
At some point in the (far) future I would like to implement a `distance` module similar to plink `--distance`. The next step after that might be a `mds` module. I wonder, though, if this should really all become part of `trident`. I wouldn't even consider analysis methods for this package if it weren't for the already  implemented `fstats`.

Adding more code increases the compilation time, is labor intensive to maintain and may weaken the profile of the software to eventually become one giant, monolithic and confusing blob.

Maybe we could come up with some clever division of modules with multiple repos or at least derived executables to keep everything small, neat and clean.

**Comment by stschiff** [comment]
Good point and in principle good idea. My rationale for fstats was to compute things directly from the repo without the need to save a forged subset. For MDS/PCA applications, my feelings were that it's more natural to first forge a subset and then take it from there... perhaps a similar argument can be made for fstats. I don't know. Worth discussing further.

**Comment by nevrome** [comment]
I think it's time to outsource the `fstats` subcommand to an own library+executable. We should certainly do so before the v1.0 release. We could call it `xerxes`, because it will beat results out of @wolfgangaroo's "sea of data". (https://en.wikipedia.org/wiki/Xerxes%27_Pontoon_Bridges)

**Comment by stschiff** [comment]
Yes I agree. I'm happy to do that (I have another analysis tool for rare variants coming up that also works with Poseidon and could make it into that as well). One reason I hadn't done it yet was the lack of a good name. That is now solved :)

**Comment by nevrome** [comment]
This is solved with [poseidon-analysis-hs](https://github.com/poseidon-framework/poseidon-analysis-hs). If I ever come around to implement distance calculation I'll do it there.
