### ISSUE TITLE
Add recommendation to general error message

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#227]
Maybe all error messages should come with a suggestion to update to the lastest/a later trident version. We're frequently fixing bugs and users should ideally not rely on outdated trident versions.

**Comment by AyGhal** [comment]
I agree!

**Comment by nevrome** [comment]
This is harder than I thought. I considered various options:

1. Check for the latest version on GitHub (https://api.github.com/repos/poseidon-framework/poseidon-hs/releases/latest) and inform the user if their version is outdated. I don't like that, because it depends on an external service. Even if we make it very robust (check if there is an internet connection first, etc.) we still build something that will certainly stop working at some point in the future. And we force tens of thousands of http requests where they aren't really necessary.
2. Amend the general error handler (as suggested in the issue here), to display a generic message along the lines of "You encountered an error - please check if the latest version fixes that.". When I thought about it I realized that this is not particularly helpful. A lot of problems where a version update helps (e.g. schema version mismatch) are actually WARNINGS, not ERRORs. And the real ERRORs are actually often unlikely to be fixed with a version update.
3. Amend the startup message. Right now we have

```
trident vX.X.X.X for poseidon v2.5.0, v2.6.0
https://poseidon-framework.github.io
```

I fear adding a sentence conveying that "there might be a new version" is pointless thanks to banner blindness.

So I'm out of ideas here. Maybe we just change the specific warning Ayshin encountered and leave it at that :shrug:

**Comment by nevrome** [comment]
@stschiff and I discussed this now. I will just change the specific warning in #231.
