### ISSUE TITLE
Wrong YAML key order

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#24]
The order of keys in the encoded POSEIDON.yml file is arbitrary and therefore confusing. It should be strictly defined.

The solution suggested [here](https://stackoverflow.com/questions/37865388/haskell-generating-json-with-aeson-gives-incorrect-order-of-fields) for Aeson did not work for me. Other solutions might build upon [Data.Yaml.Pretty](https://hackage.haskell.org/package/yaml-0.11.5.0/docs/Data-Yaml-Pretty.html) or [Data.Yaml.Builder](https://hackage.haskell.org/package/yaml-0.11.5.0/docs/Data-Yaml-Builder.html).

**Comment by stschiff** [comment]
I would vote to not define the order. We deliberately chose YAML as the format for this file, and it feels to me like tacking on an order restriction will be something that we enforce outside of the format specification. It feels weird to me. Open to discussing, obviously, and don't feel strong about it, but I would say that I could live with the fact that some YAML files will have different order.

Nothing stops us from _recommending_ implicitly a specific order, simply by using a consistent order in all of our GitHub-backed files, as well as in our help messages. But I wouldn't enforce it

**Comment by nevrome** [comment]
Right - ok - the wording above is misleading. The input order does not matter, but trident should always return files in a certain order. Just as it is now implemented in #29. Please check if you agree if this implementation.

**Comment by stschiff** [comment]
I agree.
