### ISSUE TITLE
Shorten excessively long genotype data parsing warnings just as we do with errors

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#244]
In Main-trident.hs we have a mechanism that catches every exception thrown by any subcommand and logs it neatly with `logError`. It also shortens overly long error messages, as they can occur in case of genotype data parsing failure with binary-encoded .geno files. @scarlhoff just made me aware that these long messages can also emerge as WARNINGS in `validate`. They then bypass the shortening mechanism applied to exceptions and fill the command line with hundreds of lines of gibberish.

This is something that happens rather frequently to our users and should be treated as a bug.

I'm not sure what's the best way to fix this, but the existing exception shortening is certainly not sufficient. I think I would like to keep it around, because it's cheap and covers a large range of unexpected situations. Maybe we just rework this particular error message as already requested in #224. Then it doesn't matter if it emerges as part of an error (like e.g. in `forge`) or just as a warning (as in `validate`).

**Comment by stschiff** [comment]
Upon join discussion, we identified https://github.com/poseidon-framework/poseidon-hs/blob/d53d2f0221bbe04203f0c95468600b81bbca0760/src/Poseidon/Package.hs#L376 as a possible entry point for improvement.

```
        -- ) (throwIO . PoseidonGenotypeExceptionForward)
        ) handleLowLevelException
    return pac

handleLowLevelException :: Exception -> IO ()
handleLowLevelException (AB.ParsingError e) = undefined
handleLowLevelException (AB.ParsingError e) = undefined
handleLowLevelException e = throwIO . PoseidonGenotypeExceptionForward $ e
```

**Comment by nevrome** [comment]
#299 should solve this. Error shortening is now exclusively done for genotype data parsing exceptions, but then also when they emerge on the warning log-level.
