### ISSUE TITLE
Release action should build a static binary for Apple Silicon

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#247]
Adding Apple Silicon (M1) powered macOS GitHub Action runners seems to be on GitHub's roadmap for the end of this year: https://github.com/github/roadmap/issues/528

When this feature is available we should include it into our release pipeline.

**Comment by stschiff** [comment]
Great. Not to spoil the mood, but there are now also M2 Chips 😂 (I have one in my Macbook), but probably the architecture will be comparable enough to still work with the same runner.

**Comment by nevrome** [comment]
Hm - maybe we have to check how other Haskell projects build. I'm sure we're not the only ones with this issue. I quickly looked into the [HLS GitHub actions](https://github.com/haskell/haskell-language-server/blob/master/.github/workflows/release.yaml). Difficult to read...

**Comment by nevrome** [comment]
The Apple Silicon runners are now available: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions

**Comment by nevrome** [comment]
We have such an executable since [v1.5.0.1](https://github.com/poseidon-framework/poseidon-hs/releases/tag/v1.5.0.1).
