### ISSUE TITLE
Add a global option `--ignoreChecksums` to trident

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#250]
Would have saved a lot of time during testing and debugging in the past. Of course it's technically only relevant for sub-commands that read packages, but that also applies to `--inPlinkPopName`. So I think a global option is the way to go here.

**Comment by stschiff** [comment]
Yep, good idea and easy to do. Should we perhaps not document it but treat as an internal option only? Why would average users want to do this? Perhaps if they quickly want to do something and forgot to update the checksums?

**Comment by nevrome** [comment]
Well - I see no reason to omit this option. The checksums can be a pain for everybody and sometimes it's convenient to just ignore them, e.g. when modifying a package.

Which does not mean I want to get rid of them: I feel they are useful for reviewing/monitoring changes in our public repository. And they fulfill a very important second purpose: Download validation.

**Comment by nevrome** [comment]
Closed in #263.
