### ISSUE TITLE
Split up SecondaryTypes

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#252]
As commented in PR #234, SecondaryTypes has become a bit unwieldy, and one proposal would be to factor our at least all Client-Server related types into a separate module.

**Comment by stschiff** [comment]
We might also want to define a type ExtendedIndividualInfo instead of the cryptic `([IndividualInfo], [Maybe Version], Maybe [[Maybe String]])`.

**Comment by nevrome** [comment]
The `SecondaryTypes` module does not exist any more at this point. Its content is now distributed over various different, more specific modules.
