### ISSUE TITLE
General improvements as derived from clig.dev

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#26]
I just read this great list of CLI guidelines here: https://clig.dev/. Some specific takeaways for `trident`:

- [x] [Rethink the default help text with more structure and example code](https://clig.dev/#help)
- [x]  [Add a `--plain` flag for tabular text output (e.g. `fstats`)](https://clig.dev/#help). [This interface should be very stable](https://clig.dev/#future-proofing)
- [ ] [Make sure that every command returns something in <100ms to indicate that it's not broken.](https://clig.dev/#robustness-guidelines) 
- [x] Add progress bars or at least a spinner to long operations for the same reason
- [ ] [Catch Ctrl-C for long operations (e.g. `forge`) and give useful user feedback about the command's progress before the interruption](https://clig.dev/#signals)
- [ ] [Provide pre-built binaries for `trident`](https://clig.dev/#distribution)

**Comment by stschiff** [comment]
I like all of these points!

**Comment by nevrome** [comment]
Maybe we should rename `--raw` to `--plain` if these guys say that's the standard way to name the option?

Catching Ctrl+C in forge is probably not so important any more, as my progress indication should give a good idea what already happend up to a certain point. What do you think?

**Comment by nevrome** [comment]
I think this is mostly solved. I'll make an extra issues for the pre-built binaries.
