### ISSUE TITLE
Making Inclusion/Exclusion Semantics of Forgescript more consistent

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#269]
Upon working on #264 and my updates to it (#268), I came across some inconsistencies in Forgescript that I am currently addressing in #268.

Since the change is somewhat subtle but has profound consequences on the implementation, I think it's necessary to have a clear record and documentation of this change, and I decided for an issue, which arguably makes it easier findable after all the PRs have been merged.

# Background and status quo
Forgescript has substantially evolved over the course of the last 12 months, in particular with the introduction of duplicate management, and now with the possibility to select versions of packages.

A fundamental (in my view regrettable) design choice some time ago was to make forge script queries inherently non-self-consistent. By this, I mean that for some queries entity specifications (which I call here queries) it is inherently not possible to predict the outcome by itself, without considering other queries.

## A simple example
To illustrate this, consider the following single query:

```<Ind1>```

in the context of the following list of individuals 

```
Ind1 Pop1 Pac1
Ind2 Pop1 Pac1
Ind1 Pop2 Pac2
Ind2 Pop2 Pac2
```

Now, if the query above (`<Ind1>`) would stand by itself, this would select the following:
```
Ind1 Pop1 Pac1
Ind1 Pop2 Pac2
```
which would then lead to a report of duplication in `forge` later on.

Consider now the alternative of specifying two queries:
```<Ind1>, <Pac2:Pop2:Ind1>```

Now, the outcome is
```
Ind1 Pop2 Pac2
```

So, the query `<Ind1>` cannot be considered by itself, but its outcome depends on other queries. This makes it quite hard to reason about a complex query. You might have some simple Ind-selections early on in your query, and then later one specific queries, which then "trump" the earlier queries. I think this one of the main reasons why the code has become so massively complex.

I would argue that the behaviour is in fact surprising, because ultimately a _positive_ selection somewhere later in the script leads to the _exclusion_ of a sample. 

I also think the behaviour is inconsistent when considering the larger picture of forge script semantics, see below.

It is also unnecessary, because the user has already the full power to _de-select_ whatever individuals she doesn't want. In fact, if we were to keep queries fully self-consistent, one could simply say

```<Ind1>,-<Pac1:Pop1:Ind1>```

which would lead to the same outcome.

# The larger picture

I am worried about this inconsistency, because forge script semantics have become massively complex already, even when queries are fully self-consistent. In fact, to fully describe the semantics, we already technically have to document no fewer than 12 (!) clauses:

We have six different types of queries:

1. A package with specified version, e.g. `*myPac-1.0.0*`
2. A package without specified version, e.g. `*myPac*`
3. A group, e.g. `Group1`
4. An individual, e.g. `<Sample1>`
5. A specific individual with package version, e.g. `<Pac1-1.0.0:Group1:Ind1>`
6. A specific individual without package version, e.g. `<Pac1:Group1:Ind1>`

All of these then come as both an inclusion- or an exclusion-statement, with different behaviour.

I think it's useful to write down the exact semantics of each 12 cases, the way I actually would propose them (which as I will detail below is _different_ from the current semantics):

# Suggested semantics

## Inclusion queries

* `*Pac1*`: Select all individuals in the latest version of package "Pac1"
* `*Pac1-1.0.1*`: Select all individuals in package "Pac1" with version "1.0.1"
* `Group1`: Select all individuals associated with "Group1" in all latest versions of all packages
* `<Ind1>`: Select all individuals named "Ind1" in all latest packages.
* `<Pac1:Group1:Ind1>`: Select all individuals named "Ind1" associated with "Group1" in the latest version of package "Pac1"
* `<Pac1-1.0.1:Group1:Ind1>`: Select all individuals named "Ind1" associated with "Group1" in the package "Pac1" with version "1.0.1"

## Exclusion queries

* `-*Pac1*`: Remove all individuals in all versions of package "Pac1"
* `-*Pac1-1.0.1*`: Remove only individuals in package "Pac1" with version "1.0.1" (but leave other versions in)
* `-Group1`: Remove all individuals associated with "Group1" in all versions of all packages (not just the latest)
* `-<Ind1>`: Remove all individuals named "Ind1" in all versions of all packages (not just the latest).
* `-<Pac1:Group1:Ind1>`: Remove all individuals named "Ind1" associated with "Group1" in all versions of package "Pac1"
* `-<Pac1-1.0.1:Group1:Ind1>`: Remove all individuals named "Ind1" associated with "Group1", but only if they are in "Pac1" with version "1.0.1"

# The proposed change
The suggested change to the previous behaviour is quite dramatic. The current behaviour is effectively different for four of the six inclusion statements. For example, for including individuals, if we were to write down the current behaviour above, we would have to say:
* `<Ind1>`: Select all individuals named "Ind1" in all latest packages, **except if there are other queries of the sort `<Pac:Group:Ind>`, or `<Pac-version:Group:Ind>`, in which case this query is ignored**

You might say that an ignore-clause isn't that hard to reason about, but in fact it becomes more complex for other types. For example, for Including Groups, we would currently have to write:
* `Group1`: Select all individuals associated with "Group1" in all latest versions of all packages, **except those individuals for which specific selections are present such as `<Pac:Group:Ind>`, or `<Pac-version:Group:Ind>`, in which case this query will skip those individuals**

Similar clarifications currently need to be stated for queries of type `*Pac1*` and `*Pac1-version*`, in which case again individuals may be skipped due to more specific individual queries.

So my proposed change is to remove these exclusion and exception statements and thereby make forgescript queries self-consistently predictable.

I am working on this in #268. It does affect tests quite a bit, which explicitly test of the bold-faced behaviour in the current semantics. So in #268 I am actually changing (and somewhat also simplifying) tests. I hope that this is all convincing, happy to discuss further.

**Comment by nevrome** [comment]
This was solved in trident v1.4.0.0.
