### ISSUE TITLE
Outsourcing test data with a git submodule

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#27]
When reworking the poseidon2 R package I realized that I could use exactly the same test data as in poseidon-hs. To avoid duplication I had the idea to move the data to an own git repository that could be embedded into the R and Haskell implementation repos as a [git submodule](https://github.blog/2016-02-01-working-with-submodules/). I believe this might be one of the few cases where this approach could be exactly the right one.

I tested the solution with the R package: The [test data](https://github.com/poseidon-framework/poseidonTestData) is now linked as a submodule in [`tests/testthat/`](https://github.com/poseidon-framework/poseidon2/tree/master/tests/testthat), which is indicated with a special link symbol on github:

![image](https://user-images.githubusercontent.com/10789038/103233525-a1b8af00-493d-11eb-9928-48f8a3a0e006.png)

Could this setup also work here in poseidon-hs?

**Comment by stschiff** [comment]
I'm in principle open to this, but I'm a bit anxious about the complexity of this plan. Last time I had tried git submodules I ended up not understanding them. So I'm happy to do this if you walk me through this in a live meeting.

**Comment by nevrome** [comment]
I'm not sure about this one any more. Already forgot twice that I implemented it like this over in poseidonR and ended up confused about my own code.

My idea was to provide a default test data set, which could be easily reused for new implementations. But maybe it's better to have dedicated test data, depending on what a certain tool is actually trying to achieve.

So maybe we scrap this :man_shrugging:
