### ISSUE TITLE
janno contamination consistency ignores NA

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#270]
The current implementation complains if `NA` is in the `Contamination` column, with no values in the two other required Contamination fields. That is obviously a bug, because the specification makes no semantic difference between an empty string and `NA`.

**Comment by nevrome** [comment]
Hm... I can not reproduce this. How exactly did you encode `NA`? Literally with `NA` or with the correct `n/a`? Maybe that's already the issue? Or how could I reproduce this behaviour?

Independent of that we should certainly improve the validation for these sets of columns. We already discussed this in #153 and I still think that's the right way to approach this. Also considering semantic changes we may want to apply to the schema (https://github.com/poseidon-framework/poseidon-schema/issues/64).

**Comment by stschiff** [comment]
Yeah, very sorry to have wasted your time 🙈, I used `NA`. Good learning session for me. I'll close this.
