### ISSUE TITLE
An API feature to get the complete .Janno table

### ISSUE THREAD

**Issue by 93Boy** [poseidon-framework/poseidon-hs#273]
@stschiff @nevrome I think it will be really useful to have an API feature to load the complete Poseidon data table. I have been working on the modal view of the archive explorer and I want to integrate the complete .Janno table inside the modal view.

**Comment by stschiff** [comment]
I have thought about this, and I think the most practical solution would be to provide a flag to the API to just return all janno columns, so perhaps something like `/individuals?additionalJannoColumns=ALL` ? 

From an engineering point of view that would be preferable to a new API.

If we want Janno-information for only a package or so, then I suppose it would be best to then also add a new parameter like `/individuals?additionalJannoColumns=ALL&package=2010_RasmussenNature-v2.1.1` or so?

**Comment by nevrome** [comment]
Yes - that sounds like a solid solution :+1:

**Comment by stschiff** [comment]
The `ALL` option is part of #297

**Comment by nevrome** [comment]
#297 is merged now. I'll prepare a release of trident asap to get this feature into the production server.
