### ISSUE TITLE
Issues in HTTP-communication with server

### ISSUE THREAD

**Issue by raveancic** [poseidon-framework/poseidon-hs#277]
Hi, thank you for developing this wonderful tool. I have installed it on my Mac and on an HPC server, but I keep receiving this error message 

```
trident v1.4.0.2 for poseidon v2.5.0, v2.6.0, v2.7.0, v2.7.1
https://poseidon-framework.github.io

[Info]    Download directory (will be created if missing): test
[Info]    Downloading individual list from remote
[Error]   Issues in HTTP-communication with server:
InternalException (HostCannotConnect "server.poseidon-adna.org" [Network.Socket.connect: <socket: 5>: does not exist (Connection refused)])
```

when I try to create and fetch some data from Poseidon. Is there any issue with the serve

Thank you very much.

Alessandro

**Comment by nevrome** [comment]
The server was down. I don't know why yet - will have to investigate. It's restarted now, so please try again and let me know if it works :+1:

**Comment by raveancic** [comment]
Thanks, it works now.

**Comment by nevrome** [comment]
:+1: - the reason was trivial: The VM rebooted and the server did not automatically come back.

**Comment by stschiff** [comment]
Aah yes. There was an email from the VM provider that they moved the machines somehow. Very annoying. Glad that it's resolved.
