### ISSUE TITLE
Use stack for release action

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#291]
The GitHub release action uses cabal to build the project. This causes dependency version mismatches with the stack-based infrastructure we typically use.

We should switch to stack for the release action, maybe with something like [`freckle/stack-action`](https://github.com/freckle/stack-action). I already used this for [`currycarbon`](https://github.com/nevrome/currycarbon/blob/master/.github/workflows/release.yml), but did not manage to get the windows setup right.

**Comment by stschiff** [comment]
oh boy... windows support. OK, but we do want to keep that.

**Comment by nevrome** [comment]
Finally done for v1.5.0.0 :+1:
