### ISSUE TITLE
Poseidon forge: First warnings should always be shown 

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#30]
Even without the `--warnings` flag, we might want to output the first three warnings of a type, to make the user aware that some packages might not be fully conformant in their genotype data...

**Comment by nevrome** [comment]
`--warnings` was deprecated in v1.0.0.0, when it was fully replaced by `--logMode VerboseLog`. Do you still think we should let some of these warnings bubble to the top, @stschiff? We're running without them for two years now. Maybe we can keep hiding them without any significant danger?

Please decide if you want to
- add this issue to the PPP milestone
- close it
- label it "for the future"

**Comment by stschiff** [comment]
OK, I'll close it. Thanks for looking through all the issues!
