### ISSUE TITLE
MD5 hash for .janno file different on macOS Ventura 13.6.7 (22G720)

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#302]
OK - so here's a really odd one:

@scarlhoff is currently preparing a PR for the community-archive: https://github.com/poseidon-framework/community-archive/pull/188

When she computes an MD5 hash for the .janno file locally on her macOS system (macOS Ventura 13.6.7 (22G720)) she gets a different hash than the one calculated by `trident validate` on the GitHub runner (or on my Ubuntu 22.04 system).

```
carlhoff@damp133047 2023_Carlhoff_Thailand % md5 2023_Carlhoff_Thailand.janno 
MD5 (2023_Carlhoff_Thailand.janno) = 6db278956144b175cced4b4ec1491336
```

vs.

```
schmid@im54003216:~/agora/community-archive$ md5sum 2023_Carlhoff_Thailand/*.janno
585effd3eb742d0ed0b500f1a58e0c5b  2023_Carlhoff_Thailand/2023_Carlhoff_Thailand.janno
```

It does not matter whether she uses the `MD5` tool or `trident rectify` to calculate the checksum, so this is not an issue of the tool. Maybe `MD5` and `trident` use the same underlying library, though.

This happens only for the .janno file. The hashes generated for the other package files are identical on her system and the GitHub runner (and my system).

Any ideas, @stschiff or @TCLamnidis?

**Comment by TCLamnidis** [comment]
```
$ md5sum 2023_Carlhoff_Thailand.janno 
585effd3eb742d0ed0b500f1a58e0c5b  2023_Carlhoff_Thailand.janno

$ md5 2023_Carlhoff_Thailand.janno 
MD5 (2023_Carlhoff_Thailand.janno) = 585effd3eb742d0ed0b500f1a58e0c5b
```
I do not get the same md5sum as Selina on OSX. There must be some uncommited changes on the first file.

**Comment by nevrome** [comment]
Maybe you could answer this, @scarlhoff. My understanding was that you were operating on exactly the version that was pushed to GitHub.

**Comment by scarlhoff** [comment]
Yes, this is exactly file I pushed and this happened for both my original commit from last week and the today's janno update. `trident validate` also passes locally.

**Comment by scarlhoff** [comment]
This was resolved when I created a new file and copy-pasted the content 🤷‍♀️

**Comment by nevrome** [comment]
Hm - OK. Then let's assume that this was just an odd quirk of a highly proprietary operating system, potentially its file system. Please open again when it becomes relevant once more.
