### ISSUE TITLE
Bad handling of file extensions with unpackaged genotype data in trident v1.5.7.0

### ISSUE THREAD

**Issue by smpeltola** [poseidon-framework/poseidon-hs#314]
Option -p does not correctly infer file type from the input. Example: `-p pileupcaller.double.geno `produces an error `option -p: unknown file extension: .double.geno`.

**Comment by stschiff** [comment]
Very annoying. This is a consequence of our new love for `takeExtensions`, as discussed [here](https://github.com/poseidon-framework/poseidon-hs/pull/305). We need to fix this ASAP.

**Comment by stschiff** [comment]
I pushed a PR to fix this, see #315
