### ISSUE TITLE
Changes to Package Loading interface

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#33]
We currently have a diverse zoo of functions for loading packages, such as `readPoseidonPackage`, `findPoseidonPackages`, `loadPoseidonPackagesIgnoreChecksums`, `loadPoseidonPackages` and so forth.

We discussed several steps that are needed to make this interface simpler and securer:
1. We need to integrate the base path to a package into the package data structure. This will facilitate loading of files within the package, and make the current strategy of making absolute paths obsolete. This will affect all file-loading functions (genotypes, janno, bib-file, etc.) as well as the checksum-checking.
2. We rename the loading functions. The core loading function will be renamed: `loadPoseidonPackages -> readAllPoseidonPackages`, and other functions will be renamed to make the usage of `find` and `read` consistent, and avoid `load`.
3. We remove the option to load packages with ignoring checksum-checks. Checksum-Checks are always to be done if the files can be found. If not, then not.

**Comment by nevrome** [comment]
All of this is covered now by the behemoth #29
