### ISSUE TITLE
Implement developer option for ignoring missing genotype files

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#36]
We already have a boolean flag in `readPoseidonPackageCollection` to indicate whether missing genotype files should be ignored, but we so far don't have a CLI option to trigger that behaviour. I suggest a developer option that is hidden from the help output (there is an option called `internal` in optparse-applicative, I think)

**Comment by nevrome** [comment]
Implemented in #29, though not for all modules, but only for `list` and `validate`. Modules like `summarise` and `survey` do not check for the genotype data by default, because they do not rely on them.
