### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#37]
The README is a solid user documentation, but developer documentation is missing so far. Haddock provides a way to generate good documentation, but the necessary code annotations are not available for many functions and data types. Also this documentation is not hosted anywhere at this point. 

We certainly have to add code annotation, but how do we handle the hosting of the HTML Haddock pages? Should we set up something for ourselves? Or could we consider a submission to hackage to get the same thing? I believe you already suggested that somewhere, @stschiff?

**Comment by nevrome** [comment]
For currycarbon I came up with an addition for our standard github action to automatically render and deploy haddock documentation to https://nevrome.github.io/currycarbon (not much there yet, but the setup works)

```
    - name: Render haddock documentation
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        stack haddock \
        --no-haddock-deps \
        --fast

    - name: Get path to haddock documentation
      id: haddockpath
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        docpathgeneral=`stack path --local-install-root`/doc
        echo $docpathgeneral
        docpathcurrycarbon=`find $docpathgeneral -type d -name "currycarbon*"`
        echo $docpathcurrycarbon
        echo "::set-output name=DOCPATH::$docpathcurrycarbon"
    
    - name: Deploy haddock documentation
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.haddockpath.outputs.DOCPATH }}
```

**Comment by stschiff** [comment]
This documentation deployment is super nice! Yes, I was thinking whether we should put it on Hackage (also to have even simpler means to install it, just using `stack install poseidon-hs`. But ultimately I'm not a huge fan of the hackage website. So in any case for now this seems like a brillant solution to me. Can we somehow deploy this developer documentation to a specific sub-domain under `Poseidon-framework.github.io`? Right now, that is 100% docsify.

**Comment by nevrome** [comment]
Done - I added a link in the README: https://poseidon-framework.github.io/poseidon-hs/index.html
