### ISSUE TITLE
trident fetch

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#38]
We assume that trident will often be used in conjunction with remote data repositories. These should be servers that provide on request both janno packages with all data as well as a simple top-level information data structure in JSON format to document the names and version of the packages the respective repository holds. It should also store the endpoints where the data can be requested for download.

Trident should have a module called `fetch` to download information and data from these servers. The interface could look something like this:

```
trident fetch \
  -f "*pac1*,*pac2*" \ 
  --fetchFile path/to/entity/list/file \
  -d path/to/directory/where/pacs/should/be/stored \
  --preview \
  --remote https:://...
```

- `-f` defines which entities should be downloaded (see `trident forge`). At the beginning it will only support package names
- `-f` can also be given in a file `--fetchFile`
- For this module `-d` serves as the output directory. If multiple are given, then the first is used to store new data
- `--preview` only queries the info data a given server provides to show which packages are available there for download (similar to `trident list`)
- `--remote` allows to set a repo server URL. The default would be the DAG service

Fetch should automatically handle version update detection. That means if `-d` is not empty, the local and the remote package versions should be compared and only updated data should be downloaded. If `-f` and `--fetchFile` are empty, then this should be done for all packages in all `-d`s.

**Comment by nevrome** [comment]
I just saw the nice download interface of singularity again. I think that's how I would like the fetch command line messages to look like:

```
Copying blob a4a2a29f9ba4 skipped: already exists  
Copying blob 127c9761dcba skipped: already exists  
Copying blob d13bf203e905 skipped: already exists  
Copying blob 4039240d2e0b skipped: already exists  
Copying blob 0288f53e6092 done  
Copying blob bfb2ff329e0c done  
Copying blob 0bca5c1eea79 [==================================>---] 229.9MiB / 248.2MiB
```

**Comment by stschiff** [comment]
Yes, that looks very good!

Right now, the simplest would be to use the zip-files provided by the server, and as far as I can see, their size gets projected when - for example - downloaded via a browser. So a progress bar should in principle be possible.

We should also make `fetch` clever enough to check whether a download is necessary in the first place. 

And there should perhaps be an `--all` option, simply for users who know they want everything (like our department).
