### ISSUE TITLE
Automatic haskell binary release with Github Actions

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#39]
We should have this asap to make trident more easily accessible. See here for a possible workflow: https://vrom911.github.io/blog/github-actions-releases

**Comment by nevrome** [comment]
Works now for everything except windows. There a problem with cabal-install seems to prevent successful builds.

**Comment by nevrome** [comment]
Windows builds are working now as well.

**Comment by nevrome** [comment]
Sadly I celebrated far to quickly on this one. Cabal does not produce self-contained executables, but links to libraries on the system where the binary file is executed. As these are usually missing, the executables do not work as they are now.

**Comment by nevrome** [comment]
Here's what we would have to bundle with each executable. Plus some data-files probably?
```
ldd /home/clemens/.local/bin/trident
	linux-vdso.so.1 (0x00007ffc26ded000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007feda4a97000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007feda4a7d000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007feda4a5b000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007feda4a50000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007feda4a4b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007feda4a45000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007feda49a3000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007feda47da000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007feda4c28000)
```

**Comment by nevrome** [comment]
For reference: The error I get with the binary file is actually not related to the dependencies above (:thinking:), but to a missing data-file: 

```
trident: /home/runner/.cabal/store/ghc-8.10.3/pandoc-citeproc-0.17.0.2-
cb894a372e5e093cc6d2b6c9a89c81e5657b13a289997b53dfe28685848c44ff/share/locales/locales-en-US.xml: 
openBinaryFile: does not exist (No such file or directory)
```

**Comment by stschiff** [comment]
For the record. I have removed the `unix` dependency, so the `cabal freeze` should work again, if that helps. Otherwise I think we can close this issue, right?

**Comment by nevrome** [comment]
Shall I make a tag+release for the current v0.4.2? That would be the most simple way to test the functionality of the workflow.

**Comment by stschiff** [comment]
Yes sorry I haven't done that myself

**Comment by nevrome** [comment]
All issues with the binary executables seem to be sorted out now.
