### ISSUE TITLE
verifying md5 checksums on all package reading operations is expensive

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#40]
I wonder if we should turn it off by default and let users opt-in with a `--verifyChecksums` flag. This would only be a minor CLI interface change - the reading functions already support this.

**Comment by stschiff** [comment]
Are we sure this is the major bottleneck in package loading now? If so, I totally support this. It's an easy fix and would speed things up substantially.

**Comment by nevrome** [comment]
Alright - here are five runs (in short sequence) of `time trident survey -d /projects1/poseidon/repo/ancient -d /projects1/poseidon/repo/modern` on SDAG. `survey` does not consider the genoFiles in any way.
```
real	0m13.190s 0m3.000s 0m1.605s 0m1.589s 0m1.575s
user	0m1.782s  0m1.536s 0m1.484s 0m1.508s 0m1.462s
sys	0m0.344s  0m0.174s 0m0.121s 0m0.081s 0m0.113s
```
And here I did the same with `readPoseidonPackageCollection True True baseDirs` in `runSurvey`, so to ignore the checksums:
```
real	0m12.134s 0m1.589s 0m1.673s 0m1.553s 0m1.652s
user	0m1.530s  0m1.450s 0m1.568s 0m1.452s 0m1.504s
sys	0m0.331s  0m0.132s 0m0.105s 0m0.101s 0m0.149s
```
So the checksums are no problem for functions that ignore the genoFiles (the second `true` above).

For `validate`, a module which does consider the genoFiles by default, the difference is huge. Here's `time trident validate -d /projects1/poseidon/repo/ancient -d /projects1/poseidon/repo/modern --ignoreGeno`, so validation **without** genoFile checksum checking:
```
real	0m9.776s 0m5.889s 0m1.579s 0m1.721s 0m1.624s
user	0m1.793s 0m1.530s 0m1.450s 0m1.560s 0m1.515s
sys	0m0.384s 0m0.300s 0m0.129s 0m0.161s 0m0.109s
``` 
And now the good stuff: `time trident validate -d /projects1/poseidon/repo/ancient -d /projects1/poseidon/repo/modern --ignoreGeno` **with** genoFiles checksum checking:
```
real	0m54.004s 0m37.050s 0m34.500s 0m38.299s 0m37.679s
user	0m34.785s 0m32.760s 0m32.926s 0m33.249s 0m35.513s
sys	0m2.150s  0m2.019s  0m1.572s  0m2.438s  0m2.164s
```
The difference is huge here.

**Comment by stschiff** [comment]
OK. I actually suggest to switch off checksum-checking for:

* `forge`
* `stats`
* `list`
* `survey`

I'm not sure about `summarise`. 

For the four commands above, I think we should switch it off without option to turn it on. If someone wants to check checksums, they can run `validate`. What do you think?
