### ISSUE TITLE
package.yaml

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#43]
We should switch over from an explicit definition of a cabal file to the more modern `package.yaml`, as described [here](https://docs.haskellstack.org/en/stable/stack_yaml_vs_cabal_package_file). Stack will then create a cabal-file automatically. Nothing urgent, but I think best practice with stack.

**Comment by nevrome** [comment]
hpack seems to be one solution, but there are others as well. In fact, in many job-postings I saw on the Haskell subredddit, nix was mentioned as the preferred build environment. Check out this guide: https://github.com/Gabriel439/haskell-nix

**Comment by stschiff** [comment]
Yes, nix is very interesting. I think it's like a better conda. I'd be super interested in learning it. I've tried a few years ago but failed immediately and gave up early. Happy to give it a shot again.

**Comment by nevrome** [comment]
According to this "Haskell Knowledge Map", Nix is among the most advanced topics Haskell has to offer: https://kowainik.github.io/images/Haskell_Knowledge_Map.png

But how can a build system be so complicated but still useful? Hm...

**Comment by stschiff** [comment]
Interesting image! Not sure I agree with everything on it. Anyway, Gabriel Gonzales is among my Hassell-Heroes, so I'll give his guide a thorough look!

**Comment by stschiff** [comment]
I'm closing this. Reopen if relevant.
