### ISSUE TITLE
use `hslogger` for all stderr output

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#51]
As done now in `poseidon-http-server` I suggest to switch all stderr output in the core `poseidon-hs` library to logging functions à la `infoM` or `debugM` and the like (https://hackage.haskell.org/package/hslogger-1.3.1.0/docs/System-Log-Logger.html).

This has the advantage that we can control the output from outside the library, using functions like `updateGlobalLogger` or `trapLogging`.

As a first step, we could simply replace all `hPutStrLn stderr` with `infoM`, and then add `updateGlobalLogger rootLoggerName (setLevel INFO)` to the beginning of the `main` functions in any clients. This would then literally keep behaviour exactly the same for the user. As a next step, we could use different levels, for example `debugM` for debug-messages, or `warningM` for warning messages, which would then mean we control the output with verbosity levels even from the commandline. 

Using `updateGlobalLogger` we can even channel output into files or the syslog (could be interesting for the server). 

Using `traplogging` we can control how uncaught exceptions are output. For example using the ALERT level. 

Note that all this is a "nice-to-have", not a bug-fix.

**Comment by nevrome** [comment]
To my minimal understanding `hslogger` operates fully in IO, right? Shouldn't we aspire to a more flexible and a bit more pure solution like the ReaderT pattern? I think it's sort of an industry standard. Maybe these could even be combined? But my googling revealed that for simple logging, hslogger is probably the most simple and clear solution out there.

About the ReaderT pattern: https://www.fpcomplete.com/blog/2017/06/readert-design-pattern
A simple example: https://stackoverflow.com/questions/61780295/readert-design-pattern-parametrize-the-environment

**Comment by nevrome** [comment]
There are also other logging libraries. `co-log` looks promising: https://kowainik.github.io/posts/2018-09-25-co-log

**Comment by nevrome** [comment]
Implemented now via co-log in #173
