### ISSUE TITLE
API returning individual-level data from the server

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#52]
I currently plan the following two additional APIs for the server:

* `/individuals_all` will return all individuals for all packages
* `/individuals/<package_name>` will return only individuals for the given package

How are individuals returned? I suggest to simply make a `ToJSON`-instance for `PoseidonSample` from `Janno.hs`, and then always return the entire Janno-rows as JSON. How does that sound, @nevrome ?

**Comment by nevrome** [comment]
Alright - I had multiple different ideas, but now that I thought of it, this is actually the best solution. I'm only worrying a bit about performance when `list` and `fetch` always have to download what is effectively all .janno files. 

What's the purpose of `/individuals_all`?

**Comment by stschiff** [comment]
Having thought more about this, I think I'll go with 

* `/individiduals_all` returning a JSON list of objects with only four entries: individuals, sex, group and package name
* `janno/<package_name>` returning a JSON-list with objects denoting a Janno Row for the given package

this should be a better compromise between download-speed and usability.

If at some point later needed, it wouldn't be a problem to also provide a `janno_all` API.

**Comment by stschiff** [comment]
OK. Now implemented `/individuals_all` with 87a784ddb62baca6c797c8a22be030a018279baf

**Comment by stschiff** [comment]
Reminder to self: Now that we have Janno-Rows available in the Package structures directly, I should change the `list` code to make use of that. Much better than reading all individual files each time it's run!

**Comment by stschiff** [comment]
I think it's fully done now.
