### ISSUE TITLE
Duplication check across packages

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#53]
https://github.com/poseidon-framework/data_ancient/issues/5 reminded me that trident only checks for individual/sample duplicates on the  level of individual packages. But name duplicates across packages in a repo/baseDir may cause significant issues down the line - I just saw convertf fail because of that. 

On which level should we check for duplicates? And how should we report that? Warnings? Errors?

**Comment by stschiff** [comment]
Hmm, at the very least, I think we should check for that in `forge`. Ideally even after loading packages from a base directory.
