### ISSUE TITLE
Trident init cannot find bibtex.csl

### ISSUE THREAD

**Issue by teepean** [poseidon-framework/poseidon-hs#54]
Trident init tries to find bibtex.csl from a hardcoded location. Tested with version 0.5.2. After creating the location init works fine.

C:\sr\ghc-8.10.3\poseidon-hs-0.5.2-c82cf62e4782fc85674956a1720e5ea6cc951d92\share

```
Copying genotype data
Creating new package entity
Creating POSEIDON.yml
Creating empty .janno file
Creating empty .bib file
trident-0.52.exe: PandocIOError "C:\\sr\\ghc-8.10.3\\poseidon-hs-0.5.2-c82cf62e4782fc85674956a1720e5ea6cc951d92\\share\\bibtex.csl" C:\sr\ghc-8.10.3\poseidon-hs-0.5.2-c82cf62e4782fc85674956a1720e5ea6cc951d92\share\bibtex.csl: openBinaryFile: does not exist (No such file or directory)
```

**Comment by nevrome** [comment]
Ah - thanks for reporting that. I can confirm this bug for the Linux version as well. I thought we had all these additional files covered with `cabal ... -fembed_data_files`, but apparently not.

**Comment by teepean** [comment]
I changed the title.

**Comment by nevrome** [comment]
Please try v0.5.3 - this solves the issue for me on Linux.

**Comment by teepean** [comment]
It is working on Windows as well.

**Comment by nevrome** [comment]
Great - thanks :+1:
