### ISSUE TITLE
Janno-Columns for ENA Accession IDs and other raw data source identifiers

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#59]
https://github.com/poseidon-framework/poseidon2-schema/issues/30

ENA Accession numbers could be well translated to an interesting data type: https://ena-docs.readthedocs.io/en/latest/submit/general-guide/accessions.html

**Comment by stschiff** [comment]
As I've argued in [poseidon-framework/poseidon2-schema#30](https://github.com/poseidon-framework/poseidon2-schema/issues/30), I believe we need to keep this column flexible enough to allow for a bunch of different Accession IDs, and possibly also for data sources outside of the ENA (for example NCBI). So I think while I in principle agree, the real world will probably be messier than that... sadly.

**Comment by nevrome** [comment]
This is now in #89 and #90.
