### ISSUE TITLE
readBibtex Exception handling

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#6]
We currently have `Bib.readBibtex` in use, and would like to give useful error reports in `validate`. The current implementation assumes that `readBibtex` throws `PoseidonException`, which of course is not the case. 

I'm not sure what `readBibtex` throws, but I assume it may be [CiteprocException](https://hackage.haskell.org/package/pandoc-citeproc-0.17.0.2/docs/Text-CSL-Exception.html). In that case we simply need to catch those and report them in `validate`.

**Comment by nevrome** [comment]
Should be solved.
