### ISSUE TITLE
do not check for duplicate individuals in inspection commands

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#64]
We should not check for duplicate individuals - or at least not refuse to continue if it found some. It's easy to see that users have multiple package merges lying around in a directory, and in that case it's impossible to run `list` on that directory just to see what's there.

**Comment by nevrome** [comment]
Right - I see that there might be some value in that. But I'm not convinced that this is a simple change:

- What should `list` display for the number of individuals in a group, if some individuals are there twice? 
- How should `summarise` deal with duplicates for counts and means?
- Which individuals should `forge` choose to merge?
- ...

Imho we could come up with a logic for list to handle that and only print a warning, but there are too many open questions to simply throw out the check at this point.

**Comment by stschiff** [comment]
Sorry, I was too quick in my message. I definitely think for `forge` duplicate individual IDs should be forbidden. I'm specifically talking only about the "Inspection commands", so `list`, `summarise`, `survey` and `validate`. And I think ideally we'd print a quick warning of the sort "You have duplicate individuals in your packages: X, Y, Z..." (and printing only the first three that are duplicate". 

As to the behaviours, I think in `list` we should just print out the number of individuals including duplicates. In `summarise` also, just act as if all individuals are different.

**Comment by nevrome** [comment]
Ah - ok. I misunderstood that. Makes sense like this. Let's implement it :+1:
