### ISSUE TITLE
Discussion thread for making it easier to work with large repos

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#65]
As our repository grows, we need to think about typical use cases with such large datasets. I'm listing some:

* Select (and forge) all packages from a given continent, or from several continents
* Select all packages with a given genotype SNP set (1240K or Human Origins)
* Select all individuals with a minimal SNP coverage

And then of course you can imagine that it might be useful to allow for "and" or "or" operators between these conditions in querying.

Generally, I see such queries being important mainly in the `list` and in the `forge` commands. Or we set up a new command `query`, with an ption to output a forge-file to be used with forge. So something like 

```
trident query -d /path/to/repo -q 'continent=Europe | continent=Asia' -o europe_asia_forge_file.txt
trident query -d /path/to/repo -q 'snpset=1240K & continent=NorthAmerica' -o ...
```

Maybe that's all an overkill, and we should recommend the user to use `poseidonR` in this case. I don't know...

If we don't want to go all the way to a full query-language, and alternative would perhaps be to be able to select additional output in `list` that one can then further process on the command line with awk, such as

```
trident list -d /path/to/repo --individuals --add_janno_column=Data_Type --add_janno_column=KeyWords
```
(of course, `--add_janno_column` would only be allowed for `--individuals`)

**Comment by nevrome** [comment]
Hm - maybe it's better to focus on core functionality until 1.0.0 and leave subset creation to an ecosystem that should eventually form around poseidon, if it is successful. If we put all of this on our own plate, then we also have to consider that we will have to maintain more and more code.

I like the idea to enrich the list API with janno columns though. That's straight forward and should make it way more easy to write downstream applications. Your suggested interface seems a bit cumbersome though. Maybe we could boil this down to sth. like:

```
trident list -d /path/to/repo --individuals -j "Data_Type,KeyWords"
```

**Comment by stschiff** [comment]
OK, I like this. I would still prefer to make the list interface explicit at the CLI-Parsing level, so would prefer having

```
trident list -d /path/to/repo --individuals -j Data_Type -j KeyWords
```
but I admit that's up to taste...

**Comment by stschiff** [comment]
I will make a proposal here.

**Comment by stschiff** [comment]
Just realised that in that case I will also update the Server API "/individuals_all" to return entire Janno rows instead of just some basic individual info. That way we can keep the `list` command fully symmetric between a local and the remote repository with this new extended janno column output.
