### ISSUE TITLE
Wrong output order in github actions environment

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#7]
Although the validator may not be fully complete yet I decided to replace poseidon2 already with poet in the automatic validation pipeline of data_ancient. Here's the first successful run after some configuration issues: https://github.com/poseidon-framework/data_ancient/runs/1403474318?check_suite_focus=true. The runtime should be much shorter now that the cache is filled.

The output should look like on my local system: 

```
POSEIDON.yml file consistency:
50 Poseidon packages seem to be fine
JANNO file consistency:
4778 samples seem to be fine
BIBTEX file consistency:
120 literature references seem to be fine
JANNO-BIBTEX interaction:
The following papers lack BibTeX entries: BraceDiekmannNatureEcologyEvolution2019, WangBiorxiv2020, Yang2020Science, Yu2020Cell
==> Validation passed ✓
```
Instead it looks like this:
```
50 Poseidon packages seem to be fine
4778 samples seem to be fine
120 literature references seem to be fine
POSEIDON.yml file consistency:
JANNO file consistency:
BIBTEX file consistency:
JANNO-BIBTEX interaction:
The following papers lack BibTeX entries: BraceDiekmannNatureEcologyEvolution2019, WangBiorxiv2020, Yang2020Science, Yu2020Cell
==> Validation passed ✓
```

Why that?

**Comment by stschiff** [comment]
Hmm, may have to do with lazy IO (which is why lazy bytestrings are not recommended, but cassava seems to bet on them). I'd need to look more carefully to understand this here.

**Comment by nevrome** [comment]
Apparently it was the use of `hPutStrLn` which caused the issue. Some of the messages were returned to `stderr`, others to `stdout`. I guess that caused the rearrangement. Now everything goes to `stdout` and looks fine:

```
POSEIDON.yml file consistency:
50 Poseidon packages seem to be fine
JANNO file consistency:
4778 samples seem to be fine
BIBTEX file consistency:
120 literature references seem to be fine
JANNO-BIBTEX interaction:
The following papers lack BibTeX entries: BraceDiekmannNatureEcologyEvolution2019, WangBiorxiv2020, Yang2020Science, Yu2020Cell
==> Validation passed ✓
```

Total runtime with the cache is down to 2m 49s (without active cache 41m 55s), which is acceptable. Maybe we could provide poet/trident as a precompiled executable in the future.
