### ISSUE TITLE
title: in POSEIDON.yml file when creating a new package with init

### ISSUE THREAD

**Issue by AyGhal** [poseidon-framework/poseidon-hs#80]
Now we are using, file name (-n) to fill the _title:_ in POSEIDON.yml. However, we could have situations where the name of files is our project name and the directory date of creation (e.g. 2020_Nov, 2021_March etc.). This creates an issue using forge, because trident does not recognise this as a valid package. Then we have to change it manually. Would it not be better to use directory name in title?

**Comment by nevrome** [comment]
I don't understand this. Could you give an example? `trident` should not care about directory names, and only about the package name in the POSEIDON.yml. Of course this can be identical to the directory name.

**Comment by AyGhal** [comment]
Yes, true. My bad then, I thought *package_name* is more directory name than file name.

**Comment by stschiff** [comment]
OK, I'll close this for now. Feel free to reopen @AyGhal if you would like to discuss this again.

**Comment by AyGhal** [comment]
Okay, I think it is fine like this.
