### ISSUE TITLE
validate should check the genotype data

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-hs#82]
`validate` does not check genotype data for structural correctness. This feature should probably be added (context: https://github.com/poseidon-framework/published_data/issues/6).

I believe we refrained from that so far, because we feared a massive increase in computation time for `validate`. But from my (limited) experience with broken genotype data, `forge` seems to recognize many breaking issues very soon, before much data is copied. Maybe parsing the first 1000 SNPs for each package is enough to catch most issues.

**Comment by stschiff** [comment]
OK, looking at the `readPoseidonPackageCollection` code, do you think this should be part of that? Right now, `validate` reverts completely to that function when it comes to validating packages...

**Comment by nevrome** [comment]
Right - that makes sense. We combined reading and validation and can continue to do so, if the computational cost is not too high.
