### ISSUE TITLE
`trident forge` should possibly alter the `Nr_autosomal_SNPs` entry in Janno files

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#83]
`trident forge` can result in fewer SNPs listed in the target of the forge compared to the sources. This may particularly happen if you use the `--intersect` option. I would consider it currently a bug that this isn't done, as users clearly expect the number in `Nr_autosomal_SNPs` to be related to the genotype data, and not to some abstract original calling.

**Comment by nevrome** [comment]
Ok - in a perfect world we would probably recount the number of non-missing SNPs at the end of the forge process, right? Or even offer an extra subcommand `updateJanno` to update the number. Is this what you had in mind?

**Comment by stschiff** [comment]
Uff, yes of course. Goodness. This needs to be fixed! I'll work on it.

**Comment by nevrome** [comment]
Thanks Stephan - though maybe we can merge #107 first. Probably more easy this way round.
