### ISSUE TITLE
`posPacDuplicate` seems to be a hack

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#87]
The artificial field `posPacDuplicate` in the definition of the `PoseidonPackage` data structure is a bit of an alien. It isn't really a property of a single package, more of a package collection. It is currently _only_ used in `validate`, so I believe there must be a more elegant way to solve this. Note a bug, of course.

**Comment by nevrome** [comment]
I think we could now treat this a legacy decision that may or may not be refactored out if it ever becomes relevant. I don't think we have to keep this issue open for now. Please reopen if you don't agree.
