### ISSUE TITLE
Merge Logic between genotype and janno data

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#9]
We need to implement merging logic for the case where either Janno- or Genotype files are missing, or both. We (Clemens and Stephan) suggest the following logic for merging:

- If a genotype `ind` file is missing in any of the to-be-merged packages, the created package will have *no* genotype data.
- If a janno file is missing in any of the to-be-merged packages, but an `ind` file is present for that package, fill in dummy-janno-rows from the `ind` file to create the merged package
- If both the `janno` file and the `ind` file is missing from a package, skip that package when merging (and output a warning).

This logic needs to be still implemented.

**Comment by nevrome** [comment]
Automatic creation of dummy-janno files was implemented in #29. The other points are related to #10, which may actually be abandoned.
