### ISSUE TITLE
Poseidon version and error messages

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#96]
When reading a package YAML file, we should check the Poseidon version nr. If it's outdated, we should list some helpful error messages so that the users know how to update their packages.

**Comment by nevrome** [comment]
Probably we should add a compatibility table to the homepage, which maps the fitting trident and poseidon versions to each other.

**Comment by nevrome** [comment]
The version check was implemented with #114. The remaining ToDos are for the homepage and documented here https://github.com/poseidon-framework/poseidon-framework.github.io/issues/15 and here https://github.com/poseidon-framework/poseidon-framework.github.io/issues/14
