### ISSUE TITLE
snpSet being optional

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#97]
If we go through with https://github.com/poseidon-framework/poseidon2-schema/issues/38, we still have the freedom to make `snpSet` not a `Maybe` type inside our internal data structure. We can simply interpret a missing `snpSet` field as `snpSet: Other`.

In `trident init`, I would propose to _require_ the user the input a snpSet (they can still choose Other if they want), and in `forge`, we could output a warning if `Other` is found somewhere (either because of missing or because it's explicitly set) to make sure that "Other" is "contagious" and will render any forge product to also have "Other". I think this would rarely be desired, so perhaps we can output a friendly warning, so users can update their old packages and enter a proper value there.

**Comment by nevrome** [comment]
Linked to #95
